### ISSUE TITLE
Update via OctoPrint Failed

### ISSUE THREAD

**Issue by ProtomakerSprint** [thomst08/OctoLight#1]
Update via OctoPrint Failed

++++++++++++++++++++++++++++++++
Now updating OctoLight to v0.1.6
++++++++++++++++++++++++++++++++
/home/pi/oprint/bin/python -m pip --disable-pip-version-check install https://github.com/gigibu5/OctoLight/archive/v0.1.6.zip --no-cache-dir
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting https://github.com/gigibu5/OctoLight/archive/v0.1.6.zip
ERROR: HTTP error 404 while getting https://github.com/gigibu5/OctoLight/archive/v0.1.6.zip
ERROR: Could not install requirement https://github.com/gigibu5/OctoLight/archive/v0.1.6.zip because of HTTP error 404 Client Error: Not Found for url: https://codeload.github.com/gigibu5/OctoLight/zip/v0.1.6 for URL https://github.com/gigibu5/OctoLight/archive/v0.1.6.zip

The update did not finish successfully. Please consult <code>octoprint.log</code> and <code>plugin_softwareupdate_console.log</code> for details.bug is.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Your software and hardware (please complete the following information):**
 - OctoPrint or OctoPi version: [e.g. 1.5.3]
 - Plugin version [e.g. 0.1.0]

**Additional context**

**Comment by ProtomakerSprint** [comment]
I uninstalled OctoLight Plugin and reinstalled OctoLight  seems OK

**Comment by thomst08** [comment]
Hey @ProtomakerSprint,

Thanks for letting me know about the issue.

I think this stems from one of two issues.
- OctoLight has changed repos, if you tried to update the plugin from OctoPrints, it would fail as versions 0.1.3 and prior look to the old repo to download the latest version, this can be fixed by downloading the latest version from this repo and manually installing it, otherwise you can remove the plugin and reinstall it through the package manager in OctoPrint.
- If you manually downloaded version 0.1.5 from this repo and installed it, there is a chance you installed a version that had the incorrect url to download updates from, this was corrected 24 hours after it was made live, if this is what happened, I apologise as this was my mistake, doing a manual install or removing the plugin and reinstalling will correct this. Version 0.1.5 has had this issue corrected and won't be an issue if installed again. (or later versions)

**Comment by thomst08** [comment]
I will mark this issue as closed as it appears to be an issue moving repos.
