### ISSUE TITLE
Plugin update error

### ISSUE THREAD

**Issue by Zentner77** [thomst08/OctoLight#2]
ERROR: HTTP error 404 while getting https://github.com/gigibu5/OctoLight/archive/v0.1.6.zip
ERROR: Could not install requirement https://github.com/gigibu5/OctoLight/archive/v0.1.6.zip because of HTTP error 404 Client Error: Not Found for url: https://codeload.github.com/gigibu5/OctoLight/zip/v0.1.6 for URL https://github.com/gigibu5/OctoLight/archive/v0.1.6.zip

**Comment by thomst08** [comment]
Hi @Zentner77,

Thank you for letting me know about this issue.
This issue is because this plugin has recently changed to a new repository, an you might be running an old version.
To correct this, you will need to do one of the following fixes.

- Download a copy of the newest version (found here: https://github.com/thomst08/OctoLight/releases/tag/v0.1.6) and install it manually (download the zip file)
- Remove the plugin form OctoPrint then reinstall it (be careful not to delete your settings.)

This issue is linked to this closed issue (#1) for more information.

Hope that helps, let me know if you still have issues after trying this.
